# Generated by Django 4.2 on 2023-09-25 03:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Beans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=254, verbose_name="Название типа зерна"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Brew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grind",
                    models.IntegerField(
                        default=7,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(14),
                        ],
                        verbose_name="Помол",
                    ),
                ),
                ("bean_weight", models.IntegerField(verbose_name="Вес зерен")),
                ("water_weight", models.IntegerField(verbose_name="Вес воды")),
                (
                    "temperature",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                        verbose_name="Температура воды",
                    ),
                ),
                (
                    "rate",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Оценка",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Заметки")),
                (
                    "beans",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="coffee.beans",
                        verbose_name="Тип зерна",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="brew",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("temperature__isnull", True),
                    models.Q(("temperature__gte", 0.0), ("temperature__lte", 100.0)),
                    _connector="OR",
                ),
                name="temperature_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="brew",
            constraint=models.CheckConstraint(
                check=models.Q(("grind__gte", 1), ("grind__lte", 14)),
                name="grind_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="brew",
            constraint=models.CheckConstraint(
                check=models.Q(("rate__gte", 1), ("rate__lte", 10)), name="rate_range"
            ),
        ),
    ]
